### ISSUE TITLE
创建无参数的接口

### ISSUE THREAD

**Issue by otakustay** [dancerphil/axios-interface#1]
现在的`createInterface`创建出来的函数，无论如何都是有参数的，无参数也得传个`undefined`才行，希望能有重载创建出无参的来，比如`createInterface<void, Out>`对应是无参的

**Comment by dancerphil** [comment]
给个例子，我理解 createInterface 没有这个问题，只有 request 有这个问题

**Comment by otakustay** [comment]
是我记错了，应该是`request`的问题

**Comment by dancerphil** [comment]
我会把 request 的 type inference 去掉，需要写

```typescript
const apiGetUser = (params: Params): Promise<User> => request('GET', '/user');
const apiGetUser = (): Promise<User> => request('GET', '/user');

// 相当于
const apiGetUser = createInterface<Params, User>('GET', '/user');
const apiGetUser = createInterface<void, User>('GET', '/user');
```

**Comment by otakustay** [comment]
也可以，原生的`fetch`也这样

**Comment by dancerphil** [comment]
fixed in [axios-interface@1.4.1](https://www.npmjs.com/package/axios-interface)
