### ISSUE TITLE
用基础类型作为参数的接口定义

### ISSUE THREAD

**Issue by otakustay** [dancerphil/axios-interface#2]
我经常有这样的场景，一个API接口只有一个参数，但这个参数要对应对应search里的一个key，比如按照关键字查询：`/api/search?q={keyword}`。

在定义函数的时候，希望它是只接受一个字符串参数：

```ts
type Search = (keyword: string) => Promise<Result[]>
```

但如果用`createInterface`的话，是不能这么定义的，因为不知道`keyword`参数对应`q`这个key，所以必须这么定义：

```ts
interface SearchQuery {
    q: string;
}

const search = createInterface<SearchQuery, Result[]>('GET', '/api/search');
```

这样定义会有2个问题：

1. 需要额外定义一个类型，调用时也要不断创建对象
2. 因为URL上的key的限制，入参对应的属性也叫`q`了，语义并不那么清晰

所以最终的结果，是使用`request`来实现：

```ts
const search = (keyword: string) => request('GET', '/api/search', {q: keyword}) as Promise<Result[]>;
```

有没有可能`createInterface`提供这样的参数，可以接受参数是基础类型，且映射到`data`中的一个属性上

**Comment by dancerphil** [comment]
概念上说，你可以把 onPending 的生命周期拆分出任何你想要的钩子：

```javascript
const onPending = (params, options) => {
  const { customHook, customConfig } = options;
  // ...
}

const search = createInterface(
  'GET',
  '/api/search',
  {
    customHook: () => {},
    customConfig: '...',
  }
);
```

onResolve 和 onReject 也如此
